from lib.Optimizations import optimization_epoch_number, optimization_layer_structure, optimization_regularization_weight, optimization_batch_size, optimization_layer_structure_search, optimization_momentum

__author__ = 'aviv'

