from Regularizations import weight_decay_regularization
from Regularizations import variance_regularization
from Regularizations import reconstruction_regularization
from Regularizations import weight_orthonormal_regularization
from Regularizations import hinge_regularization
from Regularizations import ortho_regularization
from Regularizations import sparse_regularization
from Regularizations import hidden_L2_regularization
from Regularizations import contractive_regularization
__author__ = 'aviv'

