from Regularizations import weight_decay_regularization
from Regularizations import pairwise_correlation_regularization
from Regularizations import reconstruction_regularization
from Regularizations import weight_orthonormal_regularization

__author__ = 'aviv'

